### PR TITLE
Refactors module to allow user to specify arbitrary config rules

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
Results of `make test`
```
PASS
ok      terraform-aws-tardigrade-config-rules/tests     559.543s

[terratest/test]: Completed successfully!
```

**Review by easttimor — CHANGES_REQUESTED** [review]
Please add some outputs for at least the config rule ARNs. Otherwise this looks great.

**Comment by lorengordon** [comment]
@easttimor added outputs and changelog notes

**Review by easttimor — APPROVED** [review]
Thanks!

**Pull request merged**
